services:
  ros2:
    build:
      context: .
      dockerfile: ros2/Dockerfile
    image: ${PROJECT_NAME:-px4ros2-jetson}-ros2:latest
    container_name: ros2
    privileged: true
    network_mode: host
    ipc: host
    runtime: nvidia
    environment:
      ZENOH_ROUTER_CONFIG_URI: /root/zenoh_config/router_config.json5
      DRONE_ID: ${DRONE_ID:-1}
    volumes:
      - /tmp:/tmp
      - /dev:/dev
      - ./zenoh_config:/root/zenoh_config
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: ros2 run rmw_zenoh_cpp rmw_zenohd

  px4:
    build:
      context: .
      dockerfile: px4/Dockerfile
    image: ${PROJECT_NAME:-px4ros2-jetson}-px4:latest
    container_name: px4
    privileged: true
    network_mode: host
    ipc: host
    environment:
      PX4_INSTANCE: 0
      DRONE_ID: ${DRONE_ID:-1}
    volumes:
      - ./start.sh:/root/start.sh
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - ros2
    command: /root/start.sh
