services:
  drone:
    image: ${PROJECT_NAME:-px4ros2-jetson}:latest
    container_name: ${CONTAINER_NAME:-px4ros2-jetson}
    privileged: true
    network_mode: host
    ipc: host
    runtime: nvidia
    volumes:
      - /tmp:/tmp
      - /dev:/dev
    environment:
      PX4_SYS_AUTOSTART: 4001
      PX4_SIM_MODEL: gz_x500
    stdin_open: true
    tty: true
    restart: unless-stopped
